Fix invalid json test for changes in Node.js
In recent versions of Node.js the error message is now:

SyntaxError: Unexpected token ] in JSON at position 190

instead of:

SyntaxError: Unexpected token ]